spring:
  application:
    name: ola-spring-cloud-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: https://olacustomerservice-1.onrender.com
              predicates:
                - Path=/customer/**

            - id: rider-service
              uri: http://localhost:8082
              predicates:
                - Path=/rider/**

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    gateway:
      access: read-only